config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :maps
  resources :static_pages
  get 'static_pages/home'
  get 'static_pages/kaarten'

  root 'static_pages#home'

  get    'kaarten'    => 'static_pages#kaarten'
  get    'webshop'    => 'static_pages#webshop'

end

app/models/map.rb
class Map < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
	 gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Gelukt' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Aangepast' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Verwijderd' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :description, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def kaarten
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frieslandopdekaart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>Friesland</title>



<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">



<!-- Custom styles for this template -->

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>



</head>
<body>

<!-- NAV -->
<div class="container-fluid"></div>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Menukaart</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="../">Home</a></li>
        <li><a href="/maps">Kaarten</a></li>
        <li><a href="#webshop">Webshop</a></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Zakelijk <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
        <li><a href="#adverteren">Adverteren</a></li>
        <li><a href="#sponsoring">Sponsoring</a></li>
        <li><a href="#adopteer">Adopteer een kaart of atlas</a></li>
        <li class="divider"></li>
        <li><a href="#donaties">Donaties</a></li>
        <li class="divider"></li>
        </ul>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contact <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#gegevens">Gegevens</a></li>
          <li><a href="#overons">Over ons</a></li>
          <li><a href="#contactform">Contactforumulier</a></li>
        </ul>
        </li>
      </ul>
         <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      Ingelogd als <strong><%= current_user.email %></strong>.
      <%= link_to 'Profiel aanpassen', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Uitloggen", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Registreren", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Inloggen", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </div>
   

  </div>
</nav>

<!-- END NAV -->
<div class="container">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
	<%= yield %>
</div>



</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> verhinderen het opslaan:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture ,"Kaart" %><br>
  <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit "Maken" %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form' %>

<%= link_to 'Weergeven', @map %> |
<%= link_to 'Terug', maps_path %>

app/views/maps/index.html.erb
<h1>Kaarten</h1>

<table>
  <thead>
    <tr>
      <th>Naam</th>
      <th>Beschrijving</th>
      <th>Kaart</th>
      <th colspan="3"></th>
    </tr>
  </thead>
        <% @maps.each do |map| %>

  <tbody>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.description %></td>
        <td><%= map.picture %></td><br>
        <td><%= link_to 'Bekijk', map %></td>
        <td><%= link_to 'Aanpassen', edit_map_path(map) %></td>
        <td><%= link_to 'Verwijderen', map, method: :delete, data: { confirm: 'Weet u het zeker?' } %></td><br>
      </tr>
  </tbody>
</table>

<br>
<% end %>

<h4><%= link_to 'Nieuwe kaart toevoegen', new_map_path %></h4>

app/views/maps/new.html.erb
<h1>Nieuwe kaart toevoegen</h1>

<%= render 'form' %>

<%= link_to 'Terug', maps_path %>

app/views/maps/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @map.description %>
</p>

<p>
  
  <%= image_tag(@map.picture_url, :width => 600) if @map.picture.present? %>
</p>

<%= link_to 'Aanpassen', edit_map_path(@map) %> |
<%= link_to 'Terug', maps_path %>

app/views/static_pages/_script.html.erb
<%= render "static_pages/script" %>
<div id='map-canvas' ></div>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>


	<!-- Google Maps API -->
	
<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();

</script>

<script>
	var map;	// Google map object
	
	// Initialize and display a google map
	function Init()
	{
		// HTML5/W3C Geolocation
		if ( navigator.geolocation )
			navigator.geolocation.getCurrentPosition( UserLocation );
		// Default to Washington, DC
		else
			window.location.reload();
			ShowLocation( 53.124938, 5.729370, "" );
	}
	
	// Callback function for asynchronous call to HTML5 geolocation
	function UserLocation( position )
	{
		ShowLocation( position.coords.latitude, position.coords.longitude, "Uw locatie" );
	}
	
	// Display a map centered at the specified coordinate with a marker and InfoWindow.
	function ShowLocation( lat, lng, title )
	{
		// Create a Google coordinate object for where to center the map
		var latlng = new google.maps.LatLng( lat, lng );	
		
		// Map options for how to display the Google map
		var mapOptions = { zoom: 11, center: latlng  };
		
		// Show the Google map in the div with the attribute id 'map-canvas'.
		map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
		
		// Place a Google Marker at the same location as the map center 
		// When you hover over the marker, it will display the title
		var marker = new google.maps.Marker( { 
			position: latlng,     
			map: map,      
			title: title
		});
		
		// Create an InfoWindow for the marker
		var contentString = "<b>" + title + "</b>";	// HTML text to display in the InfoWindow
		var infowindow = new google.maps.InfoWindow( { content: contentString } );
		
		// Set event to display the InfoWindow anchored to the marker when the marker is clicked.
		google.maps.event.addListener( marker, 'click', function() { infowindow.open( map, marker ); });
	}
	
	// Call the method 'Init()' to display the google map when the web page is displayed ( load event )
	google.maps.event.addDomListener( window, 'load', Init );

	</script>

app/views/static_pages/home.html.erb
<div class="container">
	<div class="container_1160">
		<h1><a href="/maps#index">Voeg een kaart toe</a></h1>
	</div>
</div>

app/views/static_pages/kaarten.html.erb
<div class="container_1160">
	<p>Alle kaarten</p>
			

</div>